### ISSUE TITLE
Distinct areas for the TD and AC rulings

### ISSUE THREAD

**Issue by tameware** [defiant/appealDB#3]
It would be nice to see distinct areas for the TD and AC rulings, perhaps in the summary section near the top of the page.

**Comment by defiant** [comment]
I'm not sure what you mean by this. Can you elaborate a little more.

**Comment by tameware** [comment]
For instance, on https://appealdb.com/5 it could say:

*Table Result*: 3 No Trump , made plus 3. (3n+3)
*TD Ruling*: Table result stands, 3NT by North, making six, N/S plus 690.
*AC Decision*: 5♣ by North making six, N/S plus 620, to both sides.

**Comment by tameware** [comment]
I should have used database terminology. This would entail two new text attributes, one for the TD ruling and one for the AC ruling. They'd be columns if you're using SQL.

**Comment by defiant** [comment]
pushed the changes to the repo and updated the server. Should now work as you mentioned.

**Comment by tameware** [comment]
Looks great – thanks!
